[[input]]
# list all input file in a list
# filePaths = [
#     "test_data/test_data2.txt"
# ]

# or specify just the input directory
directory = "test_data"

separator = "|"

[[output]]
# name the output file
outputFile = "output.tsv"
separator = "\t"

# each filter condition is listed below
[[filters]]

column = 16
columnType = "string"
values = [
    "LN.DARCLS",
    "LN.PROVCAT"
]

# or from a file, one line per one value
# valueFile = "filter.txt"

# or as a range (for number and datetime)
# condition = "<"
# value = 1979-05-27T07:32:00